// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://advqicvbufeskswnvjtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkdnFpY3ZidWZlc2tzd252anR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjczMTQsImV4cCI6MjA2NDQwMzMxNH0.fCymehOA66wDW1Xy82lJo-GS2Mh727GC30-EKV3fd9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);